//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMarketWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartDetails
    {
        public int CartDetailsId { get; set; }
        public short Amount { get; set; }
        public decimal ExtendedPrice { get; set; }
        public short Type { get; set; }
        public int ProductDetailsId { get; set; }
        public int CartId { get; set; }
    
        public virtual Cart Cart { get; set; }
        public virtual ProductDetails ProductDetail { get; set; }
    }
}
