//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHMarketWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewId { get; set; }
        public string Content { get; set; }
        public short OverallRating { get; set; }
        public System.DateTime ReviewDate { get; set; }
        public int UserId { get; set; }
        public int ProductId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
